<?php

namespace PV\PlateformeBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVideosByCategory($idCat){
        $qb = $this->createQueryBuilder("v")
            ->where("v.categorie = :idCat")
            ->setParameter("idCat", $idCat);

        $result = $qb->getQuery()->getResult();
    }
}
